### PR TITLE
IPython widget, loading JS the recommended way

### PR DESCRIPTION
**Pull request by TimShawver**
I added a commit on top of https://github.com/quantopian/qgrid/pull/27 to tweak the way we load the widget javascript slightly.

### CODE REVIEW

**Comment by blink1073** [comment]
Tested it, :+1:

**Comment by TimShawver** [comment]
Awesome, thanks.  I just tested on nbviewer and it looks good as well.

I'll merge this soon, but I realized that with this merge we'll stop supporting IPython 2.x.  I'm cool with that but I just want to update some docs and tag a commit as the last one that will support 2.x, so 2.x users will know how to get the version that will work for them.  I should be able to get that done in the next few days.

**Comment by TimShawver** [comment]
@blink1073 I just merged this.  Sorry about the delay, I was on vacation.  Thanks for all your hard work.  At some point I'll update the README and samples to explain the widget architecture and the show_toolbar option.

**Comment by blink1073** [comment]
Awesome! :party:

**Comment by blink1073** [comment]
Will there be a new path for the CDN files?  I tried https://cdn.rawgit.com/quantopian/qgrid/ddf33c0efb813cd574f3838f6cf1fd584b733621/qgrid/qgridjs/qgrid.editors.js and it is a 404.

**Comment by blink1073** [comment]
This works: https://cdn.rawgit.com/quantopian/qgrid/master/qgrid/qgridjs/qgrid.editors.js

**Comment by blink1073** [comment]
Ah, I see, it is tied to a commit.  This works: https://cdn.rawgit.com/quantopian/qgrid/60afa3a9928fe1a94f794c9d04e1eb5908cc6667/qgrid/qgridjs/qgrid.editors.js

**Comment by blink1073** [comment]
So, you'll have to update the link when you release a new version.

**Pull request merged**
