### PR TITLE
Fix indexing in the presence of sorting or filtering

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by TimShawver** [comment]
hey @blink1073 I'm available to look at this when it's ready.  Just ping me and I'll take a look.  I'm updating docs and will include a caveat about add/remove being experimental for now.

**Comment by blink1073** [comment]
Hi @TimShawver, this should be good to go.

**Comment by TimShawver** [comment]
@blink1073 this isn't working for me :cry:   I'm getting the same "unique id" error mentioned here: https://github.com/quantopian/qgrid/issues/59

The case I was testing was the Example 2 in the new sample notebook here: https://github.com/quantopian/qgrid/blob/master/qgrid_demo.ipynb

Could you try that out and let me know if Add/Remove work for you in that notebook?

**Comment by TimShawver** [comment]
@blink1073 looks much better.  Add/Remove seem to work, but if you remove more than one row, the following error message gets printed out for each removal.

screen shot 2016-02-22 at 3 21 03 pm

I'm going to merge anyways since this is a big improvement compared to the behavior on master right now.

**Pull request merged**
