### PR TITLE
updating jlab support

### PR DESCRIPTION
**Pull request by timkpaine**
updating for latest jupyterlab support. using typescript to avoid silent-incompatibility

### CODE REVIEW

**Comment by timkpaine** [comment]
screen shot 2017-12-05 at 3 44 45 pm

**Comment by timkpaine** [comment]
tested with 0.29.2, but will update to latest soon

**Comment by TimShawver** [comment]
Thanks, I'll try this out and include it in the next release.  I should be able to get to it within the next week or so.

**Comment by timkpaine** [comment]
cool lmk if you have questions. I converted it to typescript for safety, and because i'm only familiar with writing jlab extensions in ts.

**Comment by timkpaine** [comment]
you may have an issue with "semver: cannot find...", working to fix that with jupyterlab but it basically has to do with 1.0.0b9 vs 1.0.0-beta.9. The version disparity should probably be fixed in a separate PR

**Comment by TimShawver** [comment]
I started looking into this today and it seems like there's a new stable plugin API (maybe in juypterlab 0.30? not totally sure when it was introduced) which will allow us to handle jupyterlab support within the main qgrid npm package. This would be a big win, because I wouldn't have to publish a separate npm package for jupyterlab support every time I make a release.  Here's a PR which shows this change, in the bqplot repository, which is a widget that's maintained by on of the ipywidgets developers: https://github.com/bloomberg/bqplot/pull/566/files

I'm going to try making the same changes in the qgrid repo and see if I can get it working with 0.30 today. Just wanted to let you know so you don't spend too much time working on the separate jupyterlab npm package.

**Comment by TimShawver** [comment]
@timkpaine I merged a PR (https://github.com/quantopian/qgrid/pull/152) which I think will allow qgrid to work with jupyterlab 0.30.x, and created a new release which includes that fix. I don't think we need this PR anymore so I'm going to close it.  Thanks for opening it though, I wouldn't have known to look into updating jlab support otherwise.  Also feel free to let me know if the fix doesn't work for you for some reason. You can follow the installation steps in the README (https://github.com/quantopian/qgrid#jupyterlab-installation) to try out the fix (they've changed slightly).

**Pull request closed without merging**
